"""Export rhythmograms to PNG and SVG formats using the trace renderer."""

from PyQt6.QtCore import QSize, QRectF
from PyQt6.QtGui import QImage, QPainter
from PyQt6.QtSvg import QSvgGenerator

from core.pendulum import HarmonographConfig
from core.harmonograph import HarmonographEngine
from core.trace import TraceState
from effects.color import ColorConfig
from effects.postprocess import EffectsConfig, apply_effects
from gui.trace_renderer import draw_trace_chunk


def export_png(path: str, config: HarmonographConfig,
               color_config: ColorConfig, effects_config: EffectsConfig,
               width: int = 4096, height: int = 4096):
    """Render and save a high-resolution PNG."""
    image = _render_to_qimage(config, color_config, width, height)
    image = apply_effects(image, effects_config)
    image.save(path, "PNG")


def export_svg(path: str, config: HarmonographConfig,
               color_config: ColorConfig,
               width: int = 4096, height: int = 4096):
    """Render and save an SVG (vector, no post-processing effects)."""
    trace = TraceState(config, width, height, chunk_size=config.total_points)
    x, y = trace.compute_full_normalized()

    generator = QSvgGenerator()
    generator.setFileName(path)
    generator.setSize(QSize(width, height))
    generator.setViewBox(QRectF(0, 0, width, height))
    generator.setTitle("Rhythmogram")
    generator.setDescription("Generated by Heidersberger Rhythmogram Simulator")

    painter = QPainter(generator)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing)
    painter.fillRect(QRectF(0, 0, width, height), color_config.bg_color)

    if len(x) >= 2:
        draw_trace_chunk(painter, x, y, 0.0, 1.0, color_config,
                         trace.speed_range, width, height)
    painter.end()


def _render_to_qimage(config: HarmonographConfig, color_config: ColorConfig,
                      width: int, height: int) -> QImage:
    """Render the full trace to a QImage."""
    trace = TraceState(config, width, height, chunk_size=config.total_points)
    x, y = trace.compute_full_normalized()

    image = QImage(width, height, QImage.Format.Format_ARGB32)
    image.fill(color_config.bg_color)

    if len(x) < 2:
        return image

    painter = QPainter(image)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing)
    painter.setCompositionMode(QPainter.CompositionMode.CompositionMode_Plus)

    draw_trace_chunk(painter, x, y, 0.0, 1.0, color_config,
                     trace.speed_range, width, height)
    painter.end()
    return image
