"""Export rhythmograms to PNG and SVG formats."""

from PyQt6.QtCore import QSize, QRectF
from PyQt6.QtGui import QImage, QPainter, QPen, QColor
from PyQt6.QtSvg import QSvgGenerator

from core.pendulum import HarmonographConfig
from core.harmonograph import HarmonographEngine
from effects.color import ColorConfig
from effects.postprocess import EffectsConfig, apply_effects


def export_png(path: str, config: HarmonographConfig,
               color_config: ColorConfig, effects_config: EffectsConfig,
               width: int = 4096, height: int = 4096):
    """Render and save a high-resolution PNG."""
    image = _render_to_qimage(config, color_config, width, height)
    image = apply_effects(image, effects_config)
    image.save(path, "PNG")


def export_svg(path: str, config: HarmonographConfig,
               color_config: ColorConfig,
               width: int = 4096, height: int = 4096):
    """Render and save an SVG (vector, no effects)."""
    engine = HarmonographEngine(config)
    x, y = engine.compute_normalized(width, height)

    generator = QSvgGenerator()
    generator.setFileName(path)
    generator.setSize(QSize(width, height))
    generator.setViewBox(QRectF(0, 0, width, height))
    generator.setTitle("Rhythmogram")
    generator.setDescription("Generated by Heidersberger Rhythmogram Simulator")

    painter = QPainter(generator)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing)

    # Background
    painter.fillRect(QRectF(0, 0, width, height), color_config.bg_color)

    # Draw trace
    n = len(x)
    for i in range(n - 1):
        t = i / max(n - 1, 1)
        color = color_config.color_at(t)
        pen = QPen(color, color_config.line_width)
        painter.setPen(pen)
        painter.drawLine(int(x[i]), int(y[i]), int(x[i + 1]), int(y[i + 1]))

    painter.end()


def _render_to_qimage(config: HarmonographConfig, color_config: ColorConfig,
                      width: int, height: int) -> QImage:
    """Render the full trace to a QImage."""
    engine = HarmonographEngine(config)
    x, y = engine.compute_normalized(width, height)

    image = QImage(width, height, QImage.Format.Format_ARGB32)
    image.fill(color_config.bg_color)

    if len(x) < 2:
        return image

    painter = QPainter(image)
    painter.setRenderHint(QPainter.RenderHint.Antialiasing)
    painter.setCompositionMode(QPainter.CompositionMode.CompositionMode_Plus)

    n = len(x)
    for i in range(n - 1):
        t = i / max(n - 1, 1)
        color = color_config.color_at(t)
        pen = QPen(color, color_config.line_width)
        painter.setPen(pen)
        painter.drawLine(int(x[i]), int(y[i]), int(x[i + 1]), int(y[i + 1]))

    painter.end()
    return image
